Chasing race condition issues.

diff --git a/cli/src/main/bin/ss-create-device b/cli/src/main/bin/ss-create-device
--- a/cli/src/main/bin/ss-create-device
+++ b/cli/src/main/bin/ss-create-device
@@ -7,25 +7,44 @@ printout()
     echo \
     { \
         \"status\" : \"error\", \"error-text\" : \"$1\", \"usage\" : { \
-            \"command\" : \"ss create device DNS-NAME [TYPE]\", \
+            \"command\" : \"ss create device DNS-NAME USER PASSWORD [TYPE] [PORT]\", \
             \"arguments\" : [ \
-                { \"DNS-NAME\"  : \"The DNS name of the device. \" }, \
-                { \"TYPE\"      : \"The device type. Default:generic.\" }, \
+                { \"DNS-NAME\" : \"The DNS name of the device. \" }, \
+                { \"USER\"     : \"User name to access the device.\" }, \
+                { \"PASSWORD\" : \"Password to access the device.\" }, \
+                { \"TYPE\"     : \"The device type. Default:generic.\" }, \
+                { \"PORT\"     : \"The port of the device. Default:type specific.\" } \
             ] \
         } \
     }
 }
 
 read ACTIVE <$HOME/.sensorsink/active.env
-read NAME PASS <$HOME/.sensorsink/credentials/$ACTIVE.creds
+read ACCOUNT NAME PASS <$HOME/.sensorsink/credentials/$ACTIVE.creds
 read ENTRYHOST <$HOME/.sensorsink/$ACTIVE/host.config
 
 if [ "$1" == "" ] ; then
-    printout "Missing NAME URL ENV_CHAIN"
+    printout "Missing DNS-NAME USER PASSWORD"
     exit 1
 fi
 
 if [ "$2" == "" ] ; then
+    printout "Missing USER PASSWORD"
+    exit 1
+fi
+
+if [ "$3" == "" ] ; then
+    printout "Missing PASSWORD"
+    exit 1
+fi
+
+if [ "$4" == "" ] ; then
+    PORT_NO="-1"
+else
+    PORT_NO=$2
+fi
+
+if [ "$5" == "" ] ; then
     DEVICE_TYPE="generic"
 else
     DEVICE_TYPE=$2
@@ -33,16 +52,22 @@ fi
 
 INSPECT=`$SS_HOME/ss inspect device $1`
 EXISTS=`echo $INSPECT | grep "\"code\": 404,"`
+UNAUTHORIZED=`echo $INSPECT | grep "\"code\": 401,"`
 OTHERERROR=`echo $INSPECT | grep "\"code\": 400,"`
 if [ "$EXISTS" != "" ] ; then
   curl -qs -L --user $NAME:$PASS \
      -d "name=$1"  \
+     -d "user=$2"  \
+     -d "password=$3"  \
+     -d "port=$PORT_NO"  \
      -d "type=$DEVICE_TYPE"  \
      -H "Accept: application/json" \
-     http://$ENTRYHOST/api/1/devices/create
+     http://$ENTRYHOST/api/1/accounts/$ACCOUNT/devices/create
 elif [ "$OTHERERROR" != "" ] ; then
   ERROR=`echo $INSPECT | sed 's/.*\"description\": "//' | sed 's/\",.*//'`
   echo "ERROR: $ERROR"
+elif [ "$UNAUTHORIZED" != "" ] ; then
+  echo "ERROR: Not authorized to create device."
 else
-  echo "ERROR: Application \"$1\" already exists."
+  echo "ERROR: Device \"$1\" already exists."
 fi
diff --git a/cli/src/main/bin/ss-delete b/cli/src/main/bin/ss-delete
--- a/cli/src/main/bin/ss-delete
+++ b/cli/src/main/bin/ss-delete
@@ -8,10 +8,23 @@ cd $CURRENTDIR
 
 COMMAND=$1
 shift
+if [ -n "$2" ] ; then
+  echo "["
+  CLOSEBRACKET="true"
+fi
 
-if [ -f $SS_HOME/ss-delete-$COMMAND ]; then
-  $SS_HOME/ss-delete-$COMMAND "$@"
-else
-  echo "ERROR: Can't delete a $COMMAND"
-  exit 1
+while [ -n "$1" ] ; do
+  echo "$DELIM"
+  DELIM=","
+  if [ -f $SS_HOME/ss-inspect-$COMMAND ]; then
+    $SS_HOME/ss-delete-$COMMAND $1
+  else
+    echo "ERROR: Can't delete $COMMAND"
+    exit 1
+  fi
+  shift
+done
+
+if [ -n "$CLOSEBRACKET" ]; then
+   echo "]"
 fi
